# Nome da aplicação
spring:
  application:
    name: GS_JAVA_SOLAR_SENSE

  # Configurações do banco de dados
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm551279
    password: 230704
    driver-class-name: oracle.jdbc.OracleDriver

  # Configurações do JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction.jta.platform: org.hibernate.transaction.JTATransactionFactory

# Configuração do JWT
jwt:
  secret: "${JWT_SECRET}"


# Log IA
logging:
    level:
      org.springframework.ai: DEBUG

# Configurações de produção (desativadas)
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: false
#     properties:
#       hibernate:
#         format_sql: false
