# Nome da aplicação
spring:
  application:
    name: GS_JAVA_SOLAR_SENSE

  # Configurações do banco de dados
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm551279
    password: 230704
    driver-class-name: oracle.jdbc.OracleDriver

  # Configurações do JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction.jta.platform: org.hibernate.transaction.JTATransactionFactory

# Configuração do JWT
jwt:
  secret: "3F47v#9s8hX$U2z6AqLw9z!bXc7Pq5C@kZl3Jd6mR"

  # Configuração da OpenAI
  #ai:
    #openai:
     # api-key: "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"

# Log IA
logging:
    level:
      org.springframework.ai: DEBUG

# Configurações de produção (desativadas)
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: false
#     properties:
#       hibernate:
#         format_sql: false
